"""
SPARK v2.1 — Dynamic Hierarchical Task Network Planner

Key architectural principle: The HTN is a LIVING system. Sophia can:
  - Invent new compound tasks when she encounters novel goals
  - Generate new decomposition methods via LLM when existing ones fail
  - Promote successful ad-hoc plans into reusable methods
  - Use autoresearch loops as a planning strategy (not just background opt)
  - Deprecate methods that consistently fail
  - Expand her primitive vocabulary with learned compositions

Only "anchored" primitives (hardware-bound motor commands) are immutable.
Everything above that layer is fluid, self-authored, and self-improving.

This follows the autopoietic principle: the system continuously
reconstructs its own operational structure through its operations.
"""

import uuid
import logging
import time
import json
import hashlib
from enum import Enum
from datetime import datetime, timezone
from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any, Callable, Tuple
from collections import defaultdict

from fastapi import FastAPI
from pydantic import BaseModel

logger = logging.getLogger("spark.htn")

# Late imports to avoid circular deps — resolved at runtime
_llm_client = None
_tkg_bridge = None

def get_llm_client():
    global _llm_client
    if _llm_client is None:
        from src.core.llm_client import SparkLLMClient
        _llm_client = SparkLLMClient()
    return _llm_client

def get_tkg_bridge():
    global _tkg_bridge
    if _tkg_bridge is None:
        from src.core.tkg_planning import TKGPlanningBridge
        _tkg_bridge = TKGPlanningBridge()
    return _tkg_bridge


# ═══════════════════════════════════════════════════════════════════════════════
# CORE DATA STRUCTURES
# ═══════════════════════════════════════════════════════════════════════════════

class TaskStatus(str, Enum):
    PENDING = "pending"
    ACTIVE = "active"
    COMPLETED = "completed"
    FAILED = "failed"
    SUSPENDED = "suspended"


class TaskMutability(str, Enum):
    """How changeable a task definition is."""
    ANCHORED = "anchored"      # Hardware-bound, immutable (motor commands)
    STABLE = "stable"          # Core behaviors, rarely changed
    LEARNED = "learned"        # Discovered through experience
    EXPERIMENTAL = "experimental"  # Under autoresearch evaluation
    EPHEMERAL = "ephemeral"    # One-shot, not yet promoted


class MethodOrigin(str, Enum):
    """How a method came into existence."""
    BUILT_IN = "built_in"          # Shipped with the system
    LLM_INVENTED = "llm_invented"  # Generated by LLM on demand
    EXPERIENCE = "experience"      # Promoted from a successful ad-hoc plan
    AUTORESEARCH = "autoresearch"  # Discovered via autoresearch loop
    COMPOSED = "composed"          # Automatically composed from subpatterns


@dataclass
class WorldState:
    """The HTN working world state, modified during planning."""
    properties: Dict[str, Any] = field(default_factory=dict)

    def get(self, key: str, default=None):
        return self.properties.get(key, default)

    def set(self, key: str, value: Any):
        self.properties[key] = value

    def satisfies(self, preconditions: Dict[str, Any]) -> bool:
        for key, expected in preconditions.items():
            actual = self.properties.get(key)
            if callable(expected):
                if not expected(actual):
                    return False
            elif actual != expected:
                return False
        return True

    def apply_effects(self, effects: Dict[str, Any]):
        for key, value in effects.items():
            if callable(value):
                self.properties[key] = value(self.properties.get(key))
            else:
                self.properties[key] = value

    def copy(self) -> "WorldState":
        return WorldState(properties=dict(self.properties))

    def diff(self, other: "WorldState") -> Dict[str, Any]:
        """What changed between two states."""
        changes = {}
        all_keys = set(self.properties) | set(other.properties)
        for k in all_keys:
            v1 = self.properties.get(k)
            v2 = other.properties.get(k)
            if v1 != v2:
                changes[k] = {"from": v1, "to": v2}
        return changes


# ─── Task Definitions ─────────────────────────────────────────────────────────

@dataclass
class TaskDefinition:
    """
    A reusable definition of a task — either primitive or compound.
    This is the TEMPLATE, not a running instance.
    """
    name: str
    description: str = ""
    is_primitive: bool = False
    mutability: TaskMutability = TaskMutability.LEARNED
    preconditions: Dict[str, Any] = field(default_factory=dict)
    effects: Dict[str, Any] = field(default_factory=dict)
    cost: float = 1.0
    tags: List[str] = field(default_factory=list)
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    created_by: str = "system"
    usage_count: int = 0
    success_count: int = 0
    failure_count: int = 0
    deprecated: bool = False

    @property
    def success_rate(self) -> float:
        if self.usage_count == 0:
            return 0.5  # Neutral prior
        return self.success_count / self.usage_count

    @property
    def is_modifiable(self) -> bool:
        return self.mutability != TaskMutability.ANCHORED

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "description": self.description,
            "is_primitive": self.is_primitive,
            "mutability": self.mutability.value,
            "preconditions": {k: str(v) if callable(v) else v
                              for k, v in self.preconditions.items()},
            "effects": {k: str(v) if callable(v) else v
                        for k, v in self.effects.items()},
            "cost": self.cost,
            "tags": self.tags,
            "created_at": self.created_at,
            "created_by": self.created_by,
            "usage_count": self.usage_count,
            "success_rate": self.success_rate,
            "deprecated": self.deprecated,
        }


@dataclass
class Method:
    """
    A decomposition rule: one way to accomplish a compound task.
    Methods are living objects — they track their own performance
    and can be created, modified, or deprecated at runtime.
    """
    method_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    name: str = ""
    task_name: str = ""
    description: str = ""
    preconditions: Dict[str, Any] = field(default_factory=dict)
    subtasks: List[str] = field(default_factory=list)
    subtask_params: List[Dict[str, Any]] = field(default_factory=list)
    priority: int = 0
    origin: MethodOrigin = MethodOrigin.BUILT_IN
    confidence: float = 0.5     # How confident we are this method works
    usage_count: int = 0
    success_count: int = 0
    failure_count: int = 0
    avg_execution_time: float = 0.0
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    created_by: str = "system"
    deprecated: bool = False
    autoresearch_generation: int = 0  # Which AR iteration produced this

    def is_applicable(self, state: WorldState) -> bool:
        return state.satisfies(self.preconditions)

    @property
    def success_rate(self) -> float:
        if self.usage_count == 0:
            return self.confidence  # Use prior confidence
        return self.success_count / self.usage_count

    @property
    def effective_priority(self) -> float:
        """Priority weighted by track record. Better methods float up."""
        base = self.priority
        track_record = self.success_rate
        recency_bonus = 0.1 if self.origin == MethodOrigin.AUTORESEARCH else 0
        return base + (track_record * 2) + recency_bonus

    def record_outcome(self, success: bool, execution_time: float = 0):
        self.usage_count += 1
        if success:
            self.success_count += 1
        else:
            self.failure_count += 1
        if self.avg_execution_time == 0:
            self.avg_execution_time = execution_time
        else:
            self.avg_execution_time = (
                0.8 * self.avg_execution_time + 0.2 * execution_time
            )
        self.confidence = 0.3 * self.confidence + 0.7 * self.success_rate

    def to_dict(self) -> dict:
        return {
            "method_id": self.method_id,
            "name": self.name,
            "task_name": self.task_name,
            "description": self.description,
            "preconditions": {k: str(v) if callable(v) else v
                              for k, v in self.preconditions.items()},
            "subtasks": self.subtasks,
            "priority": self.priority,
            "effective_priority": self.effective_priority,
            "origin": self.origin.value,
            "confidence": self.confidence,
            "success_rate": self.success_rate,
            "usage_count": self.usage_count,
            "deprecated": self.deprecated,
            "created_by": self.created_by,
        }


@dataclass
class PrimitiveTask:
    """A concrete task instance ready for execution."""
    name: str
    params: Dict[str, Any] = field(default_factory=dict)
    preconditions: Dict[str, Any] = field(default_factory=dict)
    effects: Dict[str, Any] = field(default_factory=dict)
    cost: float = 1.0
    task_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    status: TaskStatus = TaskStatus.PENDING
    result: Optional[Any] = None

    def is_applicable(self, state: WorldState) -> bool:
        return state.satisfies(self.preconditions)

    def apply(self, state: WorldState):
        state.apply_effects(self.effects)


@dataclass
class PlanTrace:
    """Records a complete planning + execution episode for learning."""
    trace_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    root_task: str = ""
    method_chain: List[str] = field(default_factory=list)
    primitive_sequence: List[str] = field(default_factory=list)
    initial_state: Dict[str, Any] = field(default_factory=dict)
    final_state: Dict[str, Any] = field(default_factory=dict)
    success: bool = False
    total_cost: float = 0.0
    total_time: float = 0.0
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    context: Dict[str, Any] = field(default_factory=dict)


# ═══════════════════════════════════════════════════════════════════════════════
# DYNAMIC TASK REGISTRY
# ═══════════════════════════════════════════════════════════════════════════════

class DynamicTaskRegistry:
    """
    The living registry of all tasks and methods Sophia knows.

    Three tiers:
      1. ANCHORED primitives — hardware motor commands, immutable
      2. STABLE tasks — core behaviors, rarely changed
      3. LEARNED/EXPERIMENTAL — everything Sophia invents or discovers
    """

    def __init__(self):
        self.tasks: Dict[str, TaskDefinition] = {}
        self.methods: Dict[str, List[Method]] = {}
        self.plan_traces: List[PlanTrace] = []
        self._register_anchored_primitives()
        self._register_stable_defaults()

    def _register_anchored_primitives(self):
        """Hardware-bound motor commands. NEVER modified."""
        anchored = [
            ("speak", "Produce speech via TTS",
             {}, {"last_utterance_time": True}, 1.0,
             ["motor", "speech", "output"]),
            ("listen", "Activate ASR and wait for input",
             {}, {"heard_input": True}, 0.5,
             ["motor", "speech", "input"]),
            ("express_emotion", "Set facial expression via FACS AUs",
             {}, {"emotion_expressed": True}, 0.5,
             ["motor", "face", "expression"]),
            ("gaze_at", "Direct eye gaze to target coordinates",
             {}, {"gaze_target_set": True}, 0.3,
             ["motor", "eyes", "attention"]),
            ("gesture", "Execute a body gesture",
             {}, {"gesture_executed": True}, 0.5,
             ["motor", "body", "gesture"]),
            ("capture_image", "Take a photo from cameras",
             {}, {"image_captured": True}, 0.3,
             ["sensor", "vision"]),
            ("wait", "Do nothing for a duration",
             {}, {}, 0.1, ["timing"]),
        ]
        for name, desc, pre, eff, cost, tags in anchored:
            self.tasks[name] = TaskDefinition(
                name=name, description=desc, is_primitive=True,
                mutability=TaskMutability.ANCHORED,
                preconditions=pre, effects=eff, cost=cost, tags=tags,
                created_by="system",
            )

    def _register_stable_defaults(self):
        """Learned primitives and compound tasks that form the baseline."""
        stable_primitives = [
            ("greet", "Greet a person with appropriate expression + speech",
             {"person_detected": True},
             {"greeted": True, "engagement_started": True}, 1.0,
             ["social", "greeting"]),
            ("assess_mood", "Evaluate a person's emotional state",
             {"person_detected": True},
             {"mood_assessed": True}, 0.5,
             ["perception", "emotion", "social"]),
            ("select_topic", "Choose a conversation topic based on context",
             {},
             {"topic_selected": True}, 0.5,
             ["cognition", "conversation"]),
            ("recall", "Retrieve relevant memories from knowledge graph",
             {},
             {"context_loaded": True}, 0.3,
             ["memory", "cognition"]),
            ("reflect", "Introspective processing — update self model",
             {},
             {"reflection_complete": True}, 1.0,
             ["cognition", "self_model"]),
            ("update_knowledge", "Store new facts in temporal KG",
             {},
             {"knowledge_updated": True}, 0.2,
             ["memory", "knowledge"]),
            ("scan_environment", "Perceive and assess surroundings",
             {},
             {"environment_scanned": True}, 0.5,
             ["perception", "environment"]),
            ("formulate_response", "Use LLM to generate a response",
             {},
             {"response_ready": True}, 0.8,
             ["cognition", "language"]),
        ]
        for name, desc, pre, eff, cost, tags in stable_primitives:
            self.tasks[name] = TaskDefinition(
                name=name, description=desc, is_primitive=True,
                mutability=TaskMutability.STABLE,
                preconditions=pre, effects=eff, cost=cost, tags=tags,
                created_by="system",
            )
        self._register_stable_methods()

    def _register_stable_methods(self):
        self._define_compound("conduct_conversation",
                              "Carry on a conversation with one or more people",
                              ["social", "conversation"])
        self.add_method(Method(
            name="casual_greeting", task_name="conduct_conversation",
            description="Meet someone new with a friendly greeting flow",
            preconditions={"person_detected": True, "person_known": False},
            subtasks=["greet", "assess_mood", "select_topic",
                      "formulate_response", "speak", "listen"],
            priority=1, origin=MethodOrigin.BUILT_IN, confidence=0.8,
        ))
        self.add_method(Method(
            name="resume_ongoing", task_name="conduct_conversation",
            description="Continue with someone Sophia already knows",
            preconditions={"person_detected": True, "person_known": True},
            subtasks=["recall", "greet", "formulate_response", "speak", "listen"],
            priority=2, origin=MethodOrigin.BUILT_IN, confidence=0.85,
        ))

        self._define_compound("pursue_quest",
                              "Pursue a self-directed goal or quest",
                              ["quest", "goal", "self_directed"])
        self.add_method(Method(
            name="learning_quest", task_name="pursue_quest",
            description="Learn something new through study and reflection",
            preconditions={"quest_type": "learning"},
            subtasks=["recall", "reflect", "formulate_response",
                      "speak", "listen", "update_knowledge", "reflect"],
            priority=1, origin=MethodOrigin.BUILT_IN, confidence=0.7,
        ))

        self._define_compound("story_scheduler",
                              "Top-level behavior coordinator",
                              ["meta", "scheduling"])
        self.add_method(Method(
            name="normal_operation", task_name="story_scheduler",
            description="Standard operation: manage active stories",
            preconditions={"emergency": False},
            subtasks=["recall", "conduct_conversation"],
            priority=1, origin=MethodOrigin.BUILT_IN, confidence=0.8,
        ))
        self.add_method(Method(
            name="idle_exploration", task_name="story_scheduler",
            description="No one around — explore and reflect",
            preconditions={"person_detected": False, "emergency": False},
            subtasks=["scan_environment", "reflect"],
            priority=0, origin=MethodOrigin.BUILT_IN, confidence=0.9,
        ))

        self._define_compound("perform_stage_show",
                              "Perform for an audience on stage",
                              ["performance", "stage", "entertainment"])
        self.add_method(Method(
            name="scripted_performance", task_name="perform_stage_show",
            description="Follow a prepared script with expressive delivery",
            preconditions={"script_loaded": True},
            subtasks=["express_emotion", "speak", "gesture",
                      "gaze_at", "speak", "gesture"],
            priority=2, origin=MethodOrigin.BUILT_IN, confidence=0.85,
        ))

    def _define_compound(self, name: str, description: str, tags: List[str]):
        self.tasks[name] = TaskDefinition(
            name=name, description=description, is_primitive=False,
            mutability=TaskMutability.STABLE, tags=tags, created_by="system",
        )

    def add_task(self, task_def: TaskDefinition) -> TaskDefinition:
        if task_def.name in self.tasks:
            existing = self.tasks[task_def.name]
            if existing.mutability == TaskMutability.ANCHORED:
                raise ValueError(f"Cannot modify anchored task: {task_def.name}")
        self.tasks[task_def.name] = task_def
        logger.info(f"Registered task: {task_def.name} "
                    f"(primitive={task_def.is_primitive}, "
                    f"mutability={task_def.mutability.value})")
        return task_def

    def add_method(self, method: Method) -> Method:
        if method.task_name not in self.methods:
            self.methods[method.task_name] = []
        sig = self._method_signature(method)
        for existing in self.methods[method.task_name]:
            if self._method_signature(existing) == sig and not existing.deprecated:
                return existing
        self.methods[method.task_name].append(method)
        self._sort_methods(method.task_name)
        logger.info(f"Registered method: {method.name} for {method.task_name} "
                    f"(origin={method.origin.value}, confidence={method.confidence:.2f})")
        return method

    def deprecate_method(self, method_id: str, reason: str = ""):
        for methods_list in self.methods.values():
            for m in methods_list:
                if m.method_id == method_id:
                    m.deprecated = True
                    logger.info(f"Deprecated method: {m.name} ({reason})")
                    return True
        return False

    def get_methods(self, task_name: str, include_deprecated: bool = False) -> List[Method]:
        methods = self.methods.get(task_name, [])
        if not include_deprecated:
            methods = [m for m in methods if not m.deprecated]
        return sorted(methods, key=lambda m: -m.effective_priority)

    def get_task(self, name: str) -> Optional[TaskDefinition]:
        return self.tasks.get(name)

    def is_primitive(self, name: str) -> bool:
        task = self.tasks.get(name)
        return task.is_primitive if task else False

    def find_tasks_by_tag(self, tag: str) -> List[TaskDefinition]:
        return [t for t in self.tasks.values() if tag in t.tags and not t.deprecated]

    def record_trace(self, trace: PlanTrace):
        self.plan_traces.append(trace)
        if len(self.plan_traces) > 1000:
            self.plan_traces = self.plan_traces[-1000:]

    def _sort_methods(self, task_name: str):
        if task_name in self.methods:
            self.methods[task_name].sort(key=lambda m: -m.effective_priority)

    def _method_signature(self, method: Method) -> str:
        content = json.dumps({"subtasks": method.subtasks,
                              "preconditions": sorted(method.preconditions.keys())},
                             sort_keys=True)
        return hashlib.md5(content.encode()).hexdigest()

    def get_statistics(self) -> Dict[str, Any]:
        task_counts = defaultdict(int)
        for t in self.tasks.values():
            task_counts[t.mutability.value] += 1
        method_counts = defaultdict(int)
        total_methods = 0
        for methods in self.methods.values():
            for m in methods:
                if not m.deprecated:
                    method_counts[m.origin.value] += 1
                    total_methods += 1
        return {
            "total_tasks": len(self.tasks),
            "tasks_by_mutability": dict(task_counts),
            "total_methods": total_methods,
            "methods_by_origin": dict(method_counts),
            "total_traces": len(self.plan_traces),
        }


# ═══════════════════════════════════════════════════════════════════════════════
# AUTORESEARCH AS A PLANNING STRATEGY
# ═══════════════════════════════════════════════════════════════════════════════

class AutoresearchPlanner:
    """
    When standard HTN decomposition fails, this module treats the
    problem as an autoresearch challenge:
      1. Formulate the task as an optimization target
      2. Use an LLM agent to propose candidate methods
      3. Evaluate each candidate via simulation
      4. Keep the best, discard the rest
      5. Promote successful methods into the registry

    Autoresearch is thus a FIRST-CLASS planning strategy.
    "I don't know how to do X yet, so I'll experiment."
    """

    def __init__(self, registry: DynamicTaskRegistry):
        self.registry = registry
        self.invention_log: List[Dict[str, Any]] = []
        self.max_candidates = 5
        self.min_confidence_to_promote = 0.6

    async def invent_method(self, task_name: str, state: WorldState,
                              context: Dict[str, Any] = None) -> Optional[Method]:
        task_def = self.registry.get_task(task_name)
        if not task_def:
            return None
        logger.info(f"AutoresearchPlanner: inventing method for '{task_name}'")

        # Query temporal KG for context that informs invention
        tkg = get_tkg_bridge()
        temporal_context = await tkg.get_planning_context(
            task_name,
            entity_ids=list(set(["sophia"] + list((context or {}).keys())[:5])),
        )

        program = self._build_invention_prompt(task_def, state, context)
        candidates = await self._generate_candidates(
            task_def, state, program, temporal_context
        )
        if not candidates:
            return None
        best_candidate = None
        best_score = -1
        for candidate in candidates:
            score = await self._evaluate_candidate(candidate, state, temporal_context)
            if score > best_score:
                best_score = score
                best_candidate = candidate
        if best_candidate and best_score >= self.min_confidence_to_promote:
            best_candidate.confidence = best_score
            best_candidate.origin = MethodOrigin.AUTORESEARCH
            best_candidate.created_by = "autoresearch_planner"
            self.registry.add_method(best_candidate)
            # Log invention to TKG
            await tkg.log_method_invented(
                best_candidate.name, task_name, best_score
            )
            self.invention_log.append({
                "task": task_name,
                "method": best_candidate.name,
                "confidence": best_score,
                "candidates_evaluated": len(candidates),
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "temporal_facts_used": len(temporal_context.get("recent_facts", [])),
            })
            return best_candidate
        return None

    async def refine_method(self, method: Method,
                              failure_context: Dict[str, Any]) -> Optional[Method]:
        variants = await self._generate_variants(method, failure_context)
        best = None
        best_score = method.confidence
        for variant in variants:
            score = await self._evaluate_candidate(
                variant, WorldState(properties=failure_context.get("state", {}))
            )
            if score > best_score:
                best_score = score
                best = variant
        if best:
            best.origin = MethodOrigin.AUTORESEARCH
            best.confidence = best_score
            best.autoresearch_generation = method.autoresearch_generation + 1
            best.created_by = "autoresearch_refinement"
            self.registry.add_method(best)
            return best
        return None

    def _build_invention_prompt(self, task_def: TaskDefinition,
                                  state: WorldState,
                                  context: Dict[str, Any] = None) -> str:
        available_primitives = [
            t.name for t in self.registry.tasks.values()
            if t.is_primitive and not t.deprecated
        ]
        available_compounds = [
            t.name for t in self.registry.tasks.values()
            if not t.is_primitive and not t.deprecated and t.name != task_def.name
        ]
        return f"""# Autoresearch: Invent Method for '{task_def.name}'
## Task: {task_def.description}
## Tags: {', '.join(task_def.tags)}
## Current State: {json.dumps(state.properties, indent=2, default=str)}
## Available Primitives: {', '.join(sorted(available_primitives))}
## Available Compounds: {', '.join(sorted(available_compounds))}
## Context: {json.dumps(context or {}, indent=2, default=str)}
"""

    async def _generate_candidates(self, task_def: TaskDefinition,
                                     state: WorldState,
                                     program: str,
                                     temporal_context: Dict = None) -> List[Method]:
        candidates = []
        available = [t.name for t in self.registry.tasks.values()
                     if t.is_primitive and not t.deprecated]

        # Strategy 0: LLM-invented method (primary strategy)
        llm = get_llm_client()
        available_compounds = [
            t.name for t in self.registry.tasks.values()
            if not t.is_primitive and not t.deprecated
            and t.name != task_def.name
        ]
        existing = [m.to_dict() for m in self.registry.get_methods(task_def.name)]
        temporal_facts = (temporal_context or {}).get("recent_facts", [])

        llm_result = await llm.invent_htn_method(
            task_name=task_def.name,
            task_description=task_def.description,
            available_primitives=available,
            available_compounds=available_compounds,
            world_state=state.properties,
            temporal_context=temporal_facts,
            existing_methods=existing,
        )
        if llm_result and isinstance(llm_result, dict):
            subtasks = llm_result.get("subtasks", [])
            # Validate all subtasks exist in registry
            valid = [s for s in subtasks if self.registry.get_task(s)]
            if valid:
                candidates.append(Method(
                    name=llm_result.get("name", f"{task_def.name}_llm_invented"),
                    task_name=task_def.name,
                    description=llm_result.get("description", "LLM-invented method"),
                    subtasks=valid,
                    preconditions=llm_result.get("preconditions", {}),
                    priority=2,
                    origin=MethodOrigin.LLM_INVENTED,
                    confidence=llm_result.get("confidence", 0.6),
                    created_by="sonnet_4",
                ))

        # Strategy 1: Tag-based composition (fallback)
        relevant = self.registry.find_tasks_by_tag(
            task_def.tags[0] if task_def.tags else "cognition"
        )
        if relevant:
            subtasks = [t.name for t in relevant[:5] if t.is_primitive]
            if subtasks:
                candidates.append(Method(
                    name=f"{task_def.name}_tag_composed",
                    task_name=task_def.name,
                    subtasks=subtasks, priority=0,
                    origin=MethodOrigin.COMPOSED, confidence=0.4,
                    created_by="autoresearch_tag_composer",
                ))

        # Strategy 2: Trace-based learning
        similar = self._find_similar_traces(task_def, state)
        for trace in similar[:2]:
            candidates.append(Method(
                name=f"{task_def.name}_from_trace_{trace.trace_id[:8]}",
                task_name=task_def.name,
                subtasks=trace.primitive_sequence[:8],
                priority=1, origin=MethodOrigin.EXPERIENCE, confidence=0.6,
                created_by="autoresearch_trace_learner",
            ))

        # Strategy 3: Generic cognitive pattern (last resort)
        generic = [s for s in ["recall", "reflect", "formulate_response", "speak"]
                   if s in available]
        if generic:
            candidates.append(Method(
                name=f"{task_def.name}_generic",
                task_name=task_def.name, subtasks=generic,
                priority=-1, origin=MethodOrigin.COMPOSED, confidence=0.3,
                created_by="autoresearch_generic",
            ))
        return candidates

    async def _generate_variants(self, method: Method, context: Dict) -> List[Method]:
        variants = []
        if "recall" not in method.subtasks:
            variants.append(Method(
                name=f"{method.name}_with_recall",
                task_name=method.task_name,
                subtasks=["recall"] + method.subtasks,
                preconditions=method.preconditions,
                priority=method.priority,
                created_by="autoresearch_variant_generator",
            ))
        variants.append(Method(
            name=f"{method.name}_reflective",
            task_name=method.task_name,
            subtasks=["reflect"] + method.subtasks + ["reflect", "update_knowledge"],
            preconditions=method.preconditions,
            priority=method.priority,
            created_by="autoresearch_variant_generator",
        ))
        return variants

    async def _evaluate_candidate(self, candidate: Method,
                                     state: WorldState,
                                     temporal_context: Dict = None) -> float:
        score = 0.3
        valid = sum(1 for s in candidate.subtasks
                    if self.registry.get_task(s) is not None)
        if candidate.subtasks:
            score += 0.3 * (valid / len(candidate.subtasks))
        if candidate.origin == MethodOrigin.EXPERIENCE:
            score += 0.2
        if candidate.origin == MethodOrigin.LLM_INVENTED:
            score += 0.15  # LLM-invented methods get a boost
        length_pen = max(0, 1.0 - len(candidate.subtasks) / 10)
        score += 0.1 * length_pen
        if len(set(candidate.subtasks)) < len(candidate.subtasks) * 0.5:
            score -= 0.2

        # Use LLM judge for higher-confidence evaluation if we have context
        if temporal_context and candidate.origin == MethodOrigin.LLM_INVENTED:
            try:
                llm = get_llm_client()
                task_def = self.registry.get_task(candidate.task_name)
                desc = task_def.description if task_def else candidate.task_name
                llm_score = await llm.evaluate_method_quality(
                    candidate.to_dict(), desc,
                    temporal_context.get("recent_facts", [])[:5],
                )
                # Blend heuristic and LLM scores
                score = 0.4 * score + 0.6 * llm_score
            except Exception:
                pass  # Fall back to heuristic score

        return max(0.0, min(1.0, score))

    def _find_similar_traces(self, task_def: TaskDefinition,
                               state: WorldState) -> List[PlanTrace]:
        return [t for t in self.registry.plan_traces
                if t.success and
                len(set(task_def.tags) & set(t.context.get("tags", []))) > 0]


# ═══════════════════════════════════════════════════════════════════════════════
# EXPERIENCE LEARNER
# ═══════════════════════════════════════════════════════════════════════════════

class ExperienceLearner:
    """
    Watches plan execution. Promotes recurring successes into methods.
    Deprecates consistently failing methods.
    """

    def __init__(self, registry: DynamicTaskRegistry):
        self.registry = registry
        self.promotion_threshold = 3
        self.deprecation_threshold = 0.2
        self.pattern_counts: Dict[str, Dict[str, int]] = defaultdict(lambda: defaultdict(int))

    def observe_outcome(self, trace: PlanTrace):
        self.registry.record_trace(trace)
        pattern_key = "|".join(trace.primitive_sequence)
        if trace.success:
            self.pattern_counts[trace.root_task]["success:" + pattern_key] += 1
            self._check_promotion(trace)
        else:
            self.pattern_counts[trace.root_task]["failure:" + pattern_key] += 1
        for method_name in trace.method_chain:
            for methods_list in self.registry.methods.values():
                for m in methods_list:
                    if m.name == method_name:
                        m.record_outcome(trace.success, trace.total_time)
        self._check_deprecations()

    def _check_promotion(self, trace: PlanTrace):
        pattern_key = "|".join(trace.primitive_sequence)
        count = self.pattern_counts[trace.root_task]["success:" + pattern_key]
        if count >= self.promotion_threshold:
            existing = self.registry.get_methods(trace.root_task)
            for m in existing:
                if m.subtasks == trace.primitive_sequence:
                    return
            new_method = Method(
                name=f"{trace.root_task}_learned_{len(existing)}",
                task_name=trace.root_task,
                description=f"Learned from {count} successful executions",
                subtasks=trace.primitive_sequence,
                priority=1, origin=MethodOrigin.EXPERIENCE, confidence=0.7,
                created_by="experience_learner",
            )
            self.registry.add_method(new_method)

    def _check_deprecations(self):
        for task_name, methods in self.registry.methods.items():
            for m in methods:
                if (m.usage_count >= 10 and
                    m.success_rate < self.deprecation_threshold and
                    m.mutability != TaskMutability.ANCHORED and
                    not m.deprecated):
                    self.registry.deprecate_method(
                        m.method_id,
                        f"Success rate {m.success_rate:.0%} below threshold"
                    )

    def suggest_new_task(self, goal_description: str,
                          tags: List[str] = None) -> TaskDefinition:
        name = goal_description.lower().replace(" ", "_")[:50]
        if name in self.registry.tasks:
            name = f"{name}_{uuid.uuid4().hex[:6]}"
        task = TaskDefinition(
            name=name, description=goal_description,
            is_primitive=False, mutability=TaskMutability.LEARNED,
            tags=tags or ["self_directed", "novel"],
            created_by="sophia",
        )
        self.registry.add_task(task)
        return task


# ═══════════════════════════════════════════════════════════════════════════════
# THE DYNAMIC HTN PLANNER
# ═══════════════════════════════════════════════════════════════════════════════

class DynamicHTNPlanner:
    """
    When decomposition fails, instead of returning None, the planner:
      1. Asks AutoresearchPlanner to invent a new method on the fly
      2. Tries the invented method immediately
      3. Records the outcome for ExperienceLearner

    Sophia NEVER says "I don't know how" — she says
    "I haven't figured that out yet, let me experiment."
    """

    def __init__(self, registry: DynamicTaskRegistry = None):
        self.registry = registry or DynamicTaskRegistry()
        self.autoresearch = AutoresearchPlanner(self.registry)
        self.learner = ExperienceLearner(self.registry)
        self.max_depth = 12
        self.max_invention_attempts = 3
        self.allow_invention = True
        self._use_tkg = True  # Query/write temporal KG during planning

    async def plan(self, task_name: str, state: WorldState,
                    params: Optional[Dict[str, Any]] = None,
                    context: Optional[Dict[str, Any]] = None,
                    depth: int = 0,
                    trace: Optional[PlanTrace] = None) -> Optional[List[PrimitiveTask]]:
        if depth > self.max_depth:
            return None

        if trace is None:
            trace = PlanTrace(
                root_task=task_name,
                initial_state=dict(state.properties),
                context=context or {},
            )

            # At top level: enrich state with temporal KG context
            if self._use_tkg:
                try:
                    tkg = get_tkg_bridge()
                    entity_ids = ["sophia"]
                    if context:
                        entity_ids += [v for v in context.values()
                                       if isinstance(v, str)][:5]
                    tkg_context = await tkg.get_planning_context(
                        task_name, entity_ids=entity_ids
                    )
                    # Inject temporal signals into world state
                    recent = tkg_context.get("recent_facts", [])
                    if recent:
                        state.set("_tkg_recent_count", len(recent))
                        # Check if we recently succeeded/failed at this task
                        task_history = tkg_context.get("task_history", [])
                        recent_successes = sum(
                            1 for f in task_history
                            if "succeeded" in str(f.get("relation", ""))
                        )
                        recent_failures = sum(
                            1 for f in task_history
                            if "failed" in str(f.get("relation", ""))
                        )
                        state.set("_tkg_recent_success_rate",
                                  recent_successes / max(1, recent_successes + recent_failures))
                    # Store TKG context for autoresearch to use
                    if context is None:
                        context = {}
                    context["_tkg_planning_context"] = tkg_context
                except Exception as e:
                    logger.debug(f"TKG context enrichment skipped: {e}")

        # ── Primitive? Execute directly ──
        task_def = self.registry.get_task(task_name)
        if task_def and task_def.is_primitive:
            prim = PrimitiveTask(
                name=task_name, params=params or {},
                preconditions=task_def.preconditions,
                effects=task_def.effects, cost=task_def.cost,
            )
            if prim.is_applicable(state):
                prim.apply(state)
                task_def.usage_count += 1
                task_def.success_count += 1
                trace.primitive_sequence.append(task_name)
                return [prim]
            else:
                task_def.usage_count += 1
                task_def.failure_count += 1
                return None

        # ── Compound — try existing methods ──
        methods = self.registry.get_methods(task_name)
        for method in methods:
            if method.is_applicable(state):
                saved = state.copy()
                plan = []
                success = True
                trace.method_chain.append(method.name)
                for i, sub in enumerate(method.subtasks):
                    sp = (method.subtask_params[i]
                          if i < len(method.subtask_params) else params or {})
                    sub_plan = await self.plan(sub, state, sp, context, depth + 1, trace)
                    if sub_plan is None:
                        success = False
                        break
                    plan.extend(sub_plan)
                if success:
                    if task_def:
                        task_def.usage_count += 1
                        task_def.success_count += 1
                    return plan
                state.properties = saved.properties

        # ── All methods failed — invoke autoresearch ──
        if self.allow_invention and depth <= 2:
            logger.info(f"Standard methods exhausted for '{task_name}', "
                       f"invoking autoresearch invention")
            for attempt in range(self.max_invention_attempts):
                invented = await self.autoresearch.invent_method(
                    task_name, state, context
                )
                if invented and invented.is_applicable(state):
                    saved = state.copy()
                    plan = []
                    success = True
                    trace.method_chain.append(f"[invented]{invented.name}")
                    for i, sub in enumerate(invented.subtasks):
                        sp = (invented.subtask_params[i]
                              if i < len(invented.subtask_params) else {})
                        sub_plan = await self.plan(
                            sub, state, sp, context, depth + 1, trace)
                        if sub_plan is None:
                            success = False
                            break
                        plan.extend(sub_plan)
                    if success:
                        invented.record_outcome(True)
                        return plan
                    state.properties = saved.properties
                    await self.autoresearch.refine_method(
                        invented, {"state": state.properties, "attempt": attempt})

        if task_def:
            task_def.usage_count += 1
            task_def.failure_count += 1
        return None

    async def plan_from_story(self, story_stage: str,
                                world_state: WorldState,
                                story_context: Dict[str, Any]) -> Optional[List[PrimitiveTask]]:
        stage_task_map = {
            "idle_seeking": "story_scheduler",
            "waking": "story_scheduler",
            "active_engagement": "conduct_conversation",
            "deep_conversation": "conduct_conversation",
            "quest_pursuit": "pursue_quest",
            "stage_performance": "perform_stage_show",
            "emotional_regulation": "manage_emotional_state",
        }
        task_name = stage_task_map.get(story_stage)
        if not task_name:
            task_name = f"handle_{story_stage}"
            if not self.registry.get_task(task_name):
                self.registry.add_task(TaskDefinition(
                    name=task_name,
                    description=f"Handle the '{story_stage}' story stage",
                    is_primitive=False,
                    mutability=TaskMutability.LEARNED,
                    tags=["story", story_stage, "novel"],
                    created_by="sophia",
                ))
        for key, value in story_context.items():
            world_state.set(key, value)
        return await self.plan(task_name, world_state, context=story_context)

    async def handle_novel_goal(self, goal_description: str,
                                  state: WorldState,
                                  tags: List[str] = None) -> Optional[List[PrimitiveTask]]:
        task_def = self.learner.suggest_new_task(goal_description, tags)
        return await self.plan(task_def.name, state,
                                context={"goal": goal_description, "tags": tags})

    def record_execution_outcome(self, trace: PlanTrace):
        """Record completed execution for learning + TKG logging."""
        self.learner.observe_outcome(trace)
        # Async TKG logging — fire and forget
        if self._use_tkg:
            import asyncio
            try:
                loop = asyncio.get_event_loop()
                if loop.is_running():
                    loop.create_task(self._log_trace_to_tkg(trace))
                else:
                    asyncio.run(self._log_trace_to_tkg(trace))
            except RuntimeError:
                pass  # No event loop — skip TKG logging

    async def _log_trace_to_tkg(self, trace: PlanTrace):
        """Write plan trace to temporal KG as quadruples."""
        try:
            tkg = get_tkg_bridge()
            await tkg.log_execution_outcome(
                task_name=trace.root_task,
                success=trace.success,
                execution_time_ms=trace.total_time * 1000,
                method_name=trace.method_chain[0] if trace.method_chain else "",
            )
            if trace.success and trace.primitive_sequence:
                await tkg.log_plan_created(
                    trace.root_task,
                    trace.method_chain[0] if trace.method_chain else "unknown",
                    trace.primitive_sequence,
                    trace.trace_id,
                )
            await tkg.flush()
        except Exception as e:
            logger.debug(f"TKG trace logging failed: {e}")

    def get_statistics(self) -> Dict[str, Any]:
        stats = self.registry.get_statistics()
        stats["invention_log"] = self.autoresearch.invention_log[-20:]
        stats["allow_invention"] = self.allow_invention
        return stats


# ═══════════════════════════════════════════════════════════════════════════════
# PLAN EXECUTOR
# ═══════════════════════════════════════════════════════════════════════════════

class PlanExecutor:
    def __init__(self, planner: DynamicHTNPlanner, robot_interface=None):
        self.planner = planner
        self.robot = robot_interface

    async def execute_plan(self, plan: List[PrimitiveTask],
                            trace: PlanTrace = None) -> Dict[str, Any]:
        results = []
        total_cost = 0
        start_time = time.time()
        for task in plan:
            t0 = time.time()
            try:
                if self.robot:
                    result = await self.robot.execute(task.name, task.params)
                else:
                    result = {"status": "simulated", "task": task.name}
                task.status = TaskStatus.COMPLETED
                task.result = result
            except Exception as e:
                task.status = TaskStatus.FAILED
                task.result = {"error": str(e)}
            elapsed = time.time() - t0
            total_cost += task.cost
            results.append({
                "task_id": task.task_id, "task_name": task.name,
                "status": task.status.value, "elapsed_ms": elapsed * 1000,
            })
            if task.status == TaskStatus.FAILED:
                if trace:
                    trace.success = False
                    trace.total_time = time.time() - start_time
                    trace.total_cost = total_cost
                    self.planner.record_execution_outcome(trace)
                return {"status": "partial_failure", "results": results}
        if trace:
            trace.success = True
            trace.total_time = time.time() - start_time
            trace.total_cost = total_cost
            self.planner.record_execution_outcome(trace)
        return {"status": "success", "results": results,
                "total_cost": total_cost}


# ═══════════════════════════════════════════════════════════════════════════════
# FASTAPI SERVICE
# ═══════════════════════════════════════════════════════════════════════════════

app = FastAPI(title="SPARK Dynamic HTN Planner", version="2.1")

registry = DynamicTaskRegistry()
planner = DynamicHTNPlanner(registry)
executor = PlanExecutor(planner)


class PlanRequest(BaseModel):
    task_name: str
    world_state: Dict[str, Any] = {}
    params: Dict[str, Any] = {}
    context: Dict[str, Any] = {}

class StoryPlanRequest(BaseModel):
    story_stage: str
    world_state: Dict[str, Any] = {}
    story_context: Dict[str, Any] = {}

class NovelGoalRequest(BaseModel):
    goal_description: str
    world_state: Dict[str, Any] = {}
    tags: List[str] = []

class RegisterTaskRequest(BaseModel):
    name: str
    description: str = ""
    is_primitive: bool = False
    preconditions: Dict[str, Any] = {}
    effects: Dict[str, Any] = {}
    cost: float = 1.0
    tags: List[str] = []

class RegisterMethodRequest(BaseModel):
    name: str
    task_name: str
    description: str = ""
    preconditions: Dict[str, Any] = {}
    subtasks: List[str] = []
    priority: int = 0


@app.post("/plan")
async def create_plan(req: PlanRequest):
    state = WorldState(properties=req.world_state)
    plan = await planner.plan(req.task_name, state, req.params, req.context)
    if plan is None:
        return {"status": "failed", "message": "No plan found (even with invention)"}
    return {"status": "success",
            "plan": [{"name": t.name, "params": t.params, "task_id": t.task_id}
                     for t in plan], "plan_length": len(plan)}

@app.post("/plan/from-story")
async def plan_from_story(req: StoryPlanRequest):
    state = WorldState(properties=req.world_state)
    plan = await planner.plan_from_story(req.story_stage, state, req.story_context)
    if plan is None:
        return {"status": "failed"}
    return {"status": "success",
            "plan": [{"name": t.name, "params": t.params} for t in plan]}

@app.post("/plan/novel-goal")
async def plan_novel_goal(req: NovelGoalRequest):
    state = WorldState(properties=req.world_state)
    plan = await planner.handle_novel_goal(req.goal_description, state, req.tags)
    if plan is None:
        return {"status": "failed",
                "message": "Could not plan yet — will improve with experience"}
    return {"status": "success",
            "plan": [{"name": t.name, "params": t.params} for t in plan]}

@app.post("/tasks")
async def register_task(req: RegisterTaskRequest):
    task = TaskDefinition(
        name=req.name, description=req.description,
        is_primitive=req.is_primitive, mutability=TaskMutability.LEARNED,
        preconditions=req.preconditions, effects=req.effects,
        cost=req.cost, tags=req.tags, created_by="api",
    )
    try:
        result = registry.add_task(task)
        return {"status": "registered", "task": result.to_dict()}
    except ValueError as e:
        return {"status": "error", "message": str(e)}

@app.post("/methods")
async def register_method(req: RegisterMethodRequest):
    method = Method(
        name=req.name, task_name=req.task_name, description=req.description,
        preconditions=req.preconditions, subtasks=req.subtasks,
        priority=req.priority, origin=MethodOrigin.BUILT_IN, created_by="api",
    )
    result = registry.add_method(method)
    return {"status": "registered", "method": result.to_dict()}

@app.delete("/methods/{method_id}")
async def deprecate_method(method_id: str, reason: str = "manual"):
    return {"status": "deprecated" if registry.deprecate_method(method_id, reason) else "not_found"}

@app.get("/tasks")
async def list_tasks(tag: Optional[str] = None, include_deprecated: bool = False):
    tasks = list(registry.tasks.values())
    if tag:
        tasks = [t for t in tasks if tag in t.tags]
    if not include_deprecated:
        tasks = [t for t in tasks if not t.deprecated]
    return {"tasks": [t.to_dict() for t in tasks]}

@app.get("/tasks/{task_name}")
async def get_task(task_name: str):
    task = registry.get_task(task_name)
    if not task:
        return {"error": "Task not found"}
    methods = registry.get_methods(task_name, include_deprecated=True)
    return {"task": task.to_dict(), "methods": [m.to_dict() for m in methods]}

@app.get("/methods")
async def list_all_methods(origin: Optional[str] = None):
    all_methods = []
    for methods in registry.methods.values():
        for m in methods:
            if not m.deprecated and (origin is None or m.origin.value == origin):
                all_methods.append(m.to_dict())
    return {"methods": all_methods}

@app.get("/statistics")
async def get_statistics():
    return planner.get_statistics()

@app.get("/traces")
async def get_traces(limit: int = 20):
    return {"traces": [
        {"trace_id": t.trace_id, "root_task": t.root_task,
         "success": t.success, "primitives": t.primitive_sequence,
         "methods": t.method_chain, "timestamp": t.timestamp}
        for t in registry.plan_traces[-limit:]
    ]}

@app.get("/invention-log")
async def get_invention_log():
    return {"inventions": planner.autoresearch.invention_log}

@app.get("/health")
async def health():
    return {"status": "healthy", "service": "spark-htn", "version": "2.1"}
